module.exports = {
  GENDER: {
    MALE: "MALE",
    FEMALE: "FEMALE",
  },
  ADMIN_ROLES: {
    SUPER_ADMIN: "SUPER_ADMIN",
    ADMIN: "ADMIN",
    HOSTEL_MANAGER: "HOSTEL_MANAGER",
  },
  USER_TYPE: {
    BUSINESS: "BUSINESS",
    INDIVIDUAL: "INDIVIDUAL",
    USER: "USER",
  },
  TRANSACTION_STATUS: {
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
    PENDING: "PENDING",
    CANCELLED: "CANCELLED",
  },
  TRANSACTION_TYPE: {
    CREDIT: "CREDIT",
    DEBIT: "DEBIT",
    WITHDRAWAL: "WITHDRAWAL",
  },
  BOOKING_STATUS: {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    CANCELLED: "CANCELLED",
  },
  NOTIFICATION_TYPE: {
    BOOKING_REQUEST: "BOOKING_REQUEST",
    BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
    BOOKING_CANCELLATION: "BOOKING_CANCELLATION",
  },
  PAYMENT_STATUS: {
    PENDING: "PENDING",
    SUCCESS: "SUCCESS",
    FAILED: "FAILED",
  },
};
